# Generated by Django 4.0.8 on 2023-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menu_name_paragraphs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraphs',
            old_name='menu',
            new_name='depend',
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(to='main.paragraphs'),
        ),
    ]
