# Generated by Django 4.0.8 on 2023-04-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_menu_paragraphs_depend_menu_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraphs',
            name='depend',
        ),
    ]
