# Generated by Django 4.2 on 2023-04-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_paragraphs_depend'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphs',
            name='selfitem',
            field=models.ManyToManyField(to='main.paragraphs', verbose_name='Дочерние пункты'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(to='main.paragraphs', verbose_name='Привязанные пункты'),
        ),
    ]
