# Generated by Django 4.2 on 2023-04-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paragraphs_selfitem_alter_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='main.paragraphs', verbose_name='Привязанные пункты'),
        ),
        migrations.AlterField(
            model_name='paragraphs',
            name='selfitem',
            field=models.ManyToManyField(blank=True, null=True, to='main.paragraphs', verbose_name='Дочерние пункты'),
        ),
    ]
