# Generated by Django 4.2 on 2023-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_menu_items_alter_paragraphs_selfitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphs',
            name='selfitem',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='main.paragraphs', verbose_name='Дочерние пункты'),
        ),
    ]
