# Generated by Django 4.2 on 2023-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
