# Generated by Django 4.2 on 2023-04-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_items_slug_alter_items_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='main.items', verbose_name='Привязанные пункты'),
        ),
        migrations.DeleteModel(
            name='Paragraphs',
        ),
    ]
