# Generated by Django 4.2 on 2023-04-07 15:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_menu_items_items_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu', verbose_name='Привязано к меню'),
        ),
        migrations.AlterField(
            model_name='items',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.items', verbose_name='Родитель'),
        ),
    ]
